app:
  locale: en

spring:
  messages:
    basename: i18n/messages
  data:
    mongodb:
      database: library

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.kulygin.changelog