version: "3.8"

networks:
  backend:
    external: false
    name: backend
services:
  library-db-image:
    networks:
      - backend
    image: mongo:4.4.6
    hostname: docker-library-db
    ports:
      - 27017:27017
  library-app-image:
    networks:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - DB_HOST=docker-library-db
      - DB_PORT=27017
      - DB_NAME=library
    ports:
      - 8080:8080
    depends_on:
      - library-db-image