server:
  port: 8001

eureka:
  client:
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  #Sleuth config
  sleuth:
    sampler:
      probability: 100
  #Zipkin config
  zipkin:
    baseUrl: http://localhost:9411
  #Batch config
  batch:
    job:
      enabled: false
  #MongoDB config
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:interviewer-criteria}
  #H2 config
  datasource:
    url: jdbc:h2:mem:interviewer
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

#Mongock config
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.kulygin.criteriaservice.changelogs

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

file:
  storage:
    csv:
      path: ${APP_STORAGE:${user.home}/interviewer-stor/csv/}