server:
  port: 8080

eureka:
  client:
    fetch-registry: true

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  #Sleuth config
  sleuth:
    sampler:
      probability: 100
  #Zipkin config
  zipkin:
    baseUrl: http://localhost:9411

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

# http://appsdeveloperblog.com/zuul-api-gateway-timeout-error/
ribbon:
  ReadTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  prefix: "/common-api"