version: "3.8"

networks:
  project-server:
    external: false
    name: project-server
services:
  interviewer-db-image:
    networks:
      - project-server
    image: mongo:4.4.6
    hostname: docker-interviewer-db
    ports:
      - 27017:27017
  interviewer-app-image:
    networks:
      - project-server
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - DB_HOST=docker-interviewer-db
      - DB_PORT=27017
      - DB_NAME=interviewer
      - APP_STORAGE=
    ports:
      - 8080:8080
    depends_on:
      - interviewer-db-image