app:
  admin:
    # mySecret777
    secret-key: $2a$10$Uke6zNBEQbaDz5MVLlX8ze0.pG5bMO2aF68QpYrejxbX8uUeDJ.lq

spring:
  data:
    mongodb:
      database: library

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.kulygin.changelog