spring:
  #Batch config
  batch:
    job:
      enabled: false
  #Shell config
  shell:
    interactive:
      enabled: true
  #MongoDB config
  data:
    mongodb:
      authentication-database: none
      host: localhost
      port: 27017
      database: interviewer
  #H2 config
  datasource:
    url: jdbc:h2:mem:interviewer
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

#Mongock config
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.kulygin.changelogs

file:
  storage:
    path: ${user.home}/interviewer-stor/
app:
  admin:
    # mySecret777
    secret-key: $2a$10$Uke6zNBEQbaDz5MVLlX8ze0.pG5bMO2aF68QpYrejxbX8uUeDJ.lq

management:
  endpoints:
    web:
      base-path: /api/management
      exposure:
        include: [ 'configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'threaddump' ]
  endpoint:
    health:
      show-details: always
    jhimetrics:
      enabled: true
    logfile:
      enabled: true
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true

logging:
  file:
    name: ${user.home}/interviewer-stor/interviewer.log