#MongoDB config
spring:
  data:
    mongodb:
      authentication-database: none
      host: localhost
      port: 27017
      database: interviewer

#Mongock config
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.kulygin.changelogs