#MongoDB config
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/interviewer

#Mongock config
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.kulygin.changelogs